/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.darroyo.servicebuilder.register.service.base;

import com.darroyo.servicebuilder.register.model.PersistedUser;
import com.darroyo.servicebuilder.register.service.PersistedUserLocalService;
import com.darroyo.servicebuilder.register.service.PersistedUserLocalServiceUtil;
import com.darroyo.servicebuilder.register.service.persistence.PersistedUserPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the persisted user local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.darroyo.servicebuilder.register.service.impl.PersistedUserLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.darroyo.servicebuilder.register.service.impl.PersistedUserLocalServiceImpl
 * @generated
 */
public abstract class PersistedUserLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, PersistedUserLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PersistedUserLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PersistedUserLocalServiceUtil</code>.
	 */

	/**
	 * Adds the persisted user to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedUserLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedUser the persisted user
	 * @return the persisted user that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedUser addPersistedUser(PersistedUser persistedUser) {
		persistedUser.setNew(true);

		return persistedUserPersistence.update(persistedUser);
	}

	/**
	 * Creates a new persisted user with the primary key. Does not add the persisted user to the database.
	 *
	 * @param userId the primary key for the new persisted user
	 * @return the new persisted user
	 */
	@Override
	@Transactional(enabled = false)
	public PersistedUser createPersistedUser(String userId) {
		return persistedUserPersistence.create(userId);
	}

	/**
	 * Deletes the persisted user with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedUserLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param userId the primary key of the persisted user
	 * @return the persisted user that was removed
	 * @throws PortalException if a persisted user with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedUser deletePersistedUser(String userId)
		throws PortalException {

		return persistedUserPersistence.remove(userId);
	}

	/**
	 * Deletes the persisted user from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedUserLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedUser the persisted user
	 * @return the persisted user that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedUser deletePersistedUser(PersistedUser persistedUser) {
		return persistedUserPersistence.remove(persistedUser);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return persistedUserPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PersistedUser.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return persistedUserPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.darroyo.servicebuilder.register.model.impl.PersistedUserModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return persistedUserPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.darroyo.servicebuilder.register.model.impl.PersistedUserModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return persistedUserPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return persistedUserPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return persistedUserPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PersistedUser fetchPersistedUser(String userId) {
		return persistedUserPersistence.fetchByPrimaryKey(userId);
	}

	/**
	 * Returns the persisted user matching the UUID and group.
	 *
	 * @param uuid the persisted user's UUID
	 * @param groupId the primary key of the group
	 * @return the matching persisted user, or <code>null</code> if a matching persisted user could not be found
	 */
	@Override
	public PersistedUser fetchPersistedUserByUuidAndGroupId(
		String uuid, long groupId) {

		return persistedUserPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the persisted user with the primary key.
	 *
	 * @param userId the primary key of the persisted user
	 * @return the persisted user
	 * @throws PortalException if a persisted user with the primary key could not be found
	 */
	@Override
	public PersistedUser getPersistedUser(String userId)
		throws PortalException {

		return persistedUserPersistence.findByPrimaryKey(userId);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return persistedUserPersistence.create((String)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return persistedUserLocalService.deletePersistedUser(
			(PersistedUser)persistedModel);
	}

	@Override
	public BasePersistence<PersistedUser> getBasePersistence() {
		return persistedUserPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return persistedUserPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the persisted users matching the UUID and company.
	 *
	 * @param uuid the UUID of the persisted users
	 * @param companyId the primary key of the company
	 * @return the matching persisted users, or an empty list if no matches were found
	 */
	@Override
	public List<PersistedUser> getPersistedUsersByUuidAndCompanyId(
		String uuid, long companyId) {

		return persistedUserPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of persisted users matching the UUID and company.
	 *
	 * @param uuid the UUID of the persisted users
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of persisted users
	 * @param end the upper bound of the range of persisted users (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching persisted users, or an empty list if no matches were found
	 */
	@Override
	public List<PersistedUser> getPersistedUsersByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<PersistedUser> orderByComparator) {

		return persistedUserPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the persisted user matching the UUID and group.
	 *
	 * @param uuid the persisted user's UUID
	 * @param groupId the primary key of the group
	 * @return the matching persisted user
	 * @throws PortalException if a matching persisted user could not be found
	 */
	@Override
	public PersistedUser getPersistedUserByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return persistedUserPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the persisted users.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.darroyo.servicebuilder.register.model.impl.PersistedUserModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of persisted users
	 * @param end the upper bound of the range of persisted users (not inclusive)
	 * @return the range of persisted users
	 */
	@Override
	public List<PersistedUser> getPersistedUsers(int start, int end) {
		return persistedUserPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of persisted users.
	 *
	 * @return the number of persisted users
	 */
	@Override
	public int getPersistedUsersCount() {
		return persistedUserPersistence.countAll();
	}

	/**
	 * Updates the persisted user in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedUserLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedUser the persisted user
	 * @return the persisted user that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedUser updatePersistedUser(PersistedUser persistedUser) {
		return persistedUserPersistence.update(persistedUser);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PersistedUserLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		persistedUserLocalService = (PersistedUserLocalService)aopProxy;

		_setLocalServiceUtilService(persistedUserLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PersistedUserLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PersistedUser.class;
	}

	protected String getModelClassName() {
		return PersistedUser.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = persistedUserPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		PersistedUserLocalService persistedUserLocalService) {

		try {
			Field field = PersistedUserLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, persistedUserLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected PersistedUserLocalService persistedUserLocalService;

	@Reference
	protected PersistedUserPersistence persistedUserPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}