/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.darroyo.servicebuilder.register.model.impl;

import com.darroyo.servicebuilder.register.model.PersistedUser;
import com.darroyo.servicebuilder.register.model.PersistedUserModel;
import com.darroyo.servicebuilder.register.model.PersistedUserSoap;

import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PersistedUser service. Represents a row in the &quot;DARROYO_PersistedUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PersistedUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PersistedUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedUserImpl
 * @generated
 */
@JSON(strict = true)
public class PersistedUserModelImpl
	extends BaseModelImpl<PersistedUser> implements PersistedUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a persisted user model instance should use the <code>PersistedUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "DARROYO_PersistedUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"userId", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"surname", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"birthDate", Types.TIMESTAMP}, {"registeredOn", Types.TIMESTAMP},
		{"recaptcha", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("surname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("registeredOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("recaptcha", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DARROYO_PersistedUser (uuid_ VARCHAR(75) null,userId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,surname VARCHAR(75) null,email VARCHAR(75) null,birthDate DATE null,registeredOn DATE null,recaptcha VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table DARROYO_PersistedUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY persistedUser.registeredOn ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DARROYO_PersistedUser.registeredOn ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REGISTEREDON_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static PersistedUser toModel(PersistedUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PersistedUser model = new PersistedUserImpl();

		model.setUuid(soapModel.getUuid());
		model.setUserId(soapModel.getUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setSurname(soapModel.getSurname());
		model.setEmail(soapModel.getEmail());
		model.setBirthDate(soapModel.getBirthDate());
		model.setRegisteredOn(soapModel.getRegisteredOn());
		model.setRecaptcha(soapModel.getRecaptcha());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<PersistedUser> toModels(PersistedUserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PersistedUser> models = new ArrayList<PersistedUser>(
			soapModels.length);

		for (PersistedUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PersistedUserModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _userId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PersistedUser.class;
	}

	@Override
	public String getModelClassName() {
		return PersistedUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PersistedUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PersistedUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PersistedUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PersistedUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PersistedUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PersistedUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PersistedUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PersistedUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PersistedUser>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PersistedUser.class.getClassLoader(), PersistedUser.class,
			ModelWrapper.class);

		try {
			Constructor<PersistedUser> constructor =
				(Constructor<PersistedUser>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PersistedUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PersistedUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PersistedUser, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PersistedUser, Object>>();
		Map<String, BiConsumer<PersistedUser, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PersistedUser, ?>>();

		attributeGetterFunctions.put("uuid", PersistedUser::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<PersistedUser, String>)PersistedUser::setUuid);
		attributeGetterFunctions.put("userId", PersistedUser::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<PersistedUser, String>)PersistedUser::setUserId);
		attributeGetterFunctions.put("groupId", PersistedUser::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<PersistedUser, Long>)PersistedUser::setGroupId);
		attributeGetterFunctions.put("companyId", PersistedUser::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<PersistedUser, Long>)PersistedUser::setCompanyId);
		attributeGetterFunctions.put("userName", PersistedUser::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<PersistedUser, String>)PersistedUser::setUserName);
		attributeGetterFunctions.put(
			"createDate", PersistedUser::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<PersistedUser, Date>)PersistedUser::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", PersistedUser::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<PersistedUser, Date>)PersistedUser::setModifiedDate);
		attributeGetterFunctions.put("name", PersistedUser::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<PersistedUser, String>)PersistedUser::setName);
		attributeGetterFunctions.put("surname", PersistedUser::getSurname);
		attributeSetterBiConsumers.put(
			"surname",
			(BiConsumer<PersistedUser, String>)PersistedUser::setSurname);
		attributeGetterFunctions.put("email", PersistedUser::getEmail);
		attributeSetterBiConsumers.put(
			"email",
			(BiConsumer<PersistedUser, String>)PersistedUser::setEmail);
		attributeGetterFunctions.put("birthDate", PersistedUser::getBirthDate);
		attributeSetterBiConsumers.put(
			"birthDate",
			(BiConsumer<PersistedUser, Date>)PersistedUser::setBirthDate);
		attributeGetterFunctions.put(
			"registeredOn", PersistedUser::getRegisteredOn);
		attributeSetterBiConsumers.put(
			"registeredOn",
			(BiConsumer<PersistedUser, Date>)PersistedUser::setRegisteredOn);
		attributeGetterFunctions.put("recaptcha", PersistedUser::getRecaptcha);
		attributeSetterBiConsumers.put(
			"recaptcha",
			(BiConsumer<PersistedUser, String>)PersistedUser::setRecaptcha);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getUserId() {
		if (_userId == null) {
			return "";
		}
		else {
			return _userId;
		}
	}

	@Override
	public void setUserId(String userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUserId() {
		return getColumnOriginalValue("userId");
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getSurname() {
		if (_surname == null) {
			return "";
		}
		else {
			return _surname;
		}
	}

	@Override
	public void setSurname(String surname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_surname = surname;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public Date getBirthDate() {
		return _birthDate;
	}

	@Override
	public void setBirthDate(Date birthDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthDate = birthDate;
	}

	@JSON
	@Override
	public Date getRegisteredOn() {
		return _registeredOn;
	}

	@Override
	public void setRegisteredOn(Date registeredOn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registeredOn = registeredOn;
	}

	@JSON
	@Override
	public String getRecaptcha() {
		if (_recaptcha == null) {
			return "";
		}
		else {
			return _recaptcha;
		}
	}

	@Override
	public void setRecaptcha(String recaptcha) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recaptcha = recaptcha;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(PersistedUser.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public PersistedUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PersistedUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PersistedUserImpl persistedUserImpl = new PersistedUserImpl();

		persistedUserImpl.setUuid(getUuid());
		persistedUserImpl.setUserId(getUserId());
		persistedUserImpl.setGroupId(getGroupId());
		persistedUserImpl.setCompanyId(getCompanyId());
		persistedUserImpl.setUserName(getUserName());
		persistedUserImpl.setCreateDate(getCreateDate());
		persistedUserImpl.setModifiedDate(getModifiedDate());
		persistedUserImpl.setName(getName());
		persistedUserImpl.setSurname(getSurname());
		persistedUserImpl.setEmail(getEmail());
		persistedUserImpl.setBirthDate(getBirthDate());
		persistedUserImpl.setRegisteredOn(getRegisteredOn());
		persistedUserImpl.setRecaptcha(getRecaptcha());

		persistedUserImpl.resetOriginalValues();

		return persistedUserImpl;
	}

	@Override
	public PersistedUser cloneWithOriginalValues() {
		PersistedUserImpl persistedUserImpl = new PersistedUserImpl();

		persistedUserImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		persistedUserImpl.setUserId(
			this.<String>getColumnOriginalValue("userId"));
		persistedUserImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		persistedUserImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		persistedUserImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		persistedUserImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		persistedUserImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		persistedUserImpl.setName(this.<String>getColumnOriginalValue("name"));
		persistedUserImpl.setSurname(
			this.<String>getColumnOriginalValue("surname"));
		persistedUserImpl.setEmail(
			this.<String>getColumnOriginalValue("email"));
		persistedUserImpl.setBirthDate(
			this.<Date>getColumnOriginalValue("birthDate"));
		persistedUserImpl.setRegisteredOn(
			this.<Date>getColumnOriginalValue("registeredOn"));
		persistedUserImpl.setRecaptcha(
			this.<String>getColumnOriginalValue("recaptcha"));

		return persistedUserImpl;
	}

	@Override
	public int compareTo(PersistedUser persistedUser) {
		int value = 0;

		value = DateUtil.compareTo(
			getRegisteredOn(), persistedUser.getRegisteredOn());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PersistedUser)) {
			return false;
		}

		PersistedUser persistedUser = (PersistedUser)object;

		String primaryKey = persistedUser.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PersistedUser> toCacheModel() {
		PersistedUserCacheModel persistedUserCacheModel =
			new PersistedUserCacheModel();

		persistedUserCacheModel.uuid = getUuid();

		String uuid = persistedUserCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			persistedUserCacheModel.uuid = null;
		}

		persistedUserCacheModel.userId = getUserId();

		String userId = persistedUserCacheModel.userId;

		if ((userId != null) && (userId.length() == 0)) {
			persistedUserCacheModel.userId = null;
		}

		persistedUserCacheModel.groupId = getGroupId();

		persistedUserCacheModel.companyId = getCompanyId();

		persistedUserCacheModel.userName = getUserName();

		String userName = persistedUserCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			persistedUserCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			persistedUserCacheModel.createDate = createDate.getTime();
		}
		else {
			persistedUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			persistedUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			persistedUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		persistedUserCacheModel.name = getName();

		String name = persistedUserCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			persistedUserCacheModel.name = null;
		}

		persistedUserCacheModel.surname = getSurname();

		String surname = persistedUserCacheModel.surname;

		if ((surname != null) && (surname.length() == 0)) {
			persistedUserCacheModel.surname = null;
		}

		persistedUserCacheModel.email = getEmail();

		String email = persistedUserCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			persistedUserCacheModel.email = null;
		}

		Date birthDate = getBirthDate();

		if (birthDate != null) {
			persistedUserCacheModel.birthDate = birthDate.getTime();
		}
		else {
			persistedUserCacheModel.birthDate = Long.MIN_VALUE;
		}

		Date registeredOn = getRegisteredOn();

		if (registeredOn != null) {
			persistedUserCacheModel.registeredOn = registeredOn.getTime();
		}
		else {
			persistedUserCacheModel.registeredOn = Long.MIN_VALUE;
		}

		persistedUserCacheModel.recaptcha = getRecaptcha();

		String recaptcha = persistedUserCacheModel.recaptcha;

		if ((recaptcha != null) && (recaptcha.length() == 0)) {
			persistedUserCacheModel.recaptcha = null;
		}

		return persistedUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PersistedUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PersistedUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PersistedUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PersistedUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PersistedUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PersistedUser)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PersistedUser>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _userId;
	private long _groupId;
	private long _companyId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _surname;
	private String _email;
	private Date _birthDate;
	private Date _registeredOn;
	private String _recaptcha;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PersistedUser, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PersistedUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("surname", _surname);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("birthDate", _birthDate);
		_columnOriginalValues.put("registeredOn", _registeredOn);
		_columnOriginalValues.put("recaptcha", _recaptcha);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("userId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("surname", 256L);

		columnBitmasks.put("email", 512L);

		columnBitmasks.put("birthDate", 1024L);

		columnBitmasks.put("registeredOn", 2048L);

		columnBitmasks.put("recaptcha", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PersistedUser _escapedModel;

}